version: "3.6"

networks:
  cr-net: # shared container network     

volumes:
  shared-data: # shared voume between the two containers
 
services:
  REST-API:
    build: 
      context: ./REST_API # Docker image is rebuild from directory
    depends_on: 
      - cron-job # cron job container needs to start first
    container_name: rest-api
    image: rest_api_pub
    networks:
      - cr-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-data:/src/shared-data
    ports:
      - "3838:3838"
    restart: always

  cron-job:
    build: 
      context: ./cron
    container_name: cron-job
    image: cron_job_pub
    networks:
      - cr-net 
    volumes:
      - shared-data:/src/shared-data
    restart: always

 
 
