version: "3.6"

services:
  rest-api:
    container_name: restful-api
    build: 
      context: ./rest_api # Docker image is rebuild from directory which contains Dockerfile
    volumes:
      - ./shared_data:/shared_data
    ports:
      - "7000:8000"
    restart: always
    
  nginx:
    container_name: nginx-reverseproxy
    image: nginx:1.9
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
     - rest-api
  
  # cron-job:
  #   build: 
  #     context: ./cron 
  #   container_name: cron-job
  #   networks:
  #     - cr-net 
  #   volumes:
  #     - shared_data:/src/shared_data
  #   restart: always
  # 

 